name: Tests Python 3.13

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-pypoetry313-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pypoetry313-

    - name: Install application dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel poetry
        poetry env use 3.13
        poetry install

    - name: Run tests
      run: |
        make test
